import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Suspense } from "react";
import Loading from "@/components/Loading";
import Footer from "@/components/Footer";
import NextTopLoader from "nextjs-toploader";
// import NextNProgress from "nextjs-progressbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Suspense fallback={<Loading />}>
          {/* <NextNProgress /> */}
          <NextTopLoader />
          <NavBar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
